# Generated by Django 2.2 on 2023-01-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Автор')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок объявления')),
                ('descriptions', models.CharField(max_length=1000, verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('publication_start_date', models.DateTimeField(auto_now_add=True)),
                ('publication_end_date', models.DateTimeField(default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.AdvertisementAuthor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.AdvertisementCategory')),
            ],
        ),
    ]
