# Generated by Django 2.2 on 2023-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='descriptions',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
