# Generated by Django 2.2 on 2023-01-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0008_advertisementnumberviews_advertisementtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='advertisementNumberViews',
        ),
        migrations.AddField(
            model_name='advertisements',
            name='numberViews',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
