# Generated by Django 2.2 on 2023-01-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0009_auto_20230105_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.AdvertisementType'),
        ),
    ]
