# Generated by Django 4.1.5 on 2023-02-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
