# Generated by Django 4.1.5 on 2023-02-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0005_blogimage_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_blogs.blog'),
            preserve_default=False,
        ),
    ]
