# Generated by Django 4.1.5 on 2023-01-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='shopapp.user'),
            preserve_default=False,
        ),
    ]
