# Generated by Django 4.1.5 on 2023-01-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
    ]
