# Generated by Django 4.1.5 on 2023-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_product_alter_userprofile_balance_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('promo_code', models.CharField(max_length=10, verbose_name='Промокод')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Скидки',
            },
        ),
    ]
