# Generated by Django 4.1.5 on 2023-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_alter_offer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
