# Generated by Django 4.1.5 on 2023-04-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
