# Generated by Django 4.2 on 2023-05-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_housing', '0002_news_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published_at',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
