# Generated by Django 4.2 on 2023-05-06 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_housing', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
