# Generated by Django 4.1.5 on 2023-01-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_newsmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
