# Generated by Django 4.1.5 on 2023-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_rename_content_commentmodel_content_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
