# Generated by Django 4.1.5 on 2023-01-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=10000, verbose_name='Содержание')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_editing', models.DateTimeField(auto_now=True)),
                ('activity', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mane', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('id_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.news')),
            ],
        ),
    ]
