# Generated by Django 4.1.5 on 2023-01-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date_create',
            new_name='date_creation',
        ),
    ]
