# Generated by Django 4.1.5 on 2023-01-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_rename_date_create_news_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_mane',
            new_name='user_name',
        ),
    ]
