# Generated by Django 4.1.5 on 2023-01-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_rename_user_mane_comment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_comment',
            new_name='news',
        ),
    ]
