# Generated by Django 4.1.5 on 2023-01-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='news',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_news.newsmodel'),
            preserve_default=False,
        ),
    ]
