# Generated by Django 4.1.5 on 2023-01-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_commentmodel_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='author',
            field=models.CharField(default='', max_length=20, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
