# Generated by Django 4.1.5 on 2023-01-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_alter_newsmodel_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
