# Generated by Django 4.1.5 on 2023-01-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_alter_commentmodel_user_alter_newsmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='content',
            new_name='content_comment',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='content',
            new_name='content_news',
        ),
    ]
