# Generated by Django 4.1.5 on 2023-02-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_commentmodel_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'permissions': [('can_publish', 'Может публиковать')]},
        ),
    ]
