# Generated by Django 4.1.5 on 2023-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_alter_newsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
